language: python

python:
    - "2.7"

env:
    - DJANGO=1_4
    - DJANGO=1_7

install: "pip install -r test-projects/common.pip -r test-projects/django_${DJANGO}/setup.pip"

script: "cd test-projects/django_${DJANGO} && python manage.py test pubsubpull${TESTS}"
